### ISSUE TITLE
Public/private keys undefined for Vagrant

### ISSUE THREAD

**Issue by rgladwell** [voxpupuli/hiera-eyaml#101]
For some reason when I run a puppet script using hiera-eyaml the default values for the public and private keys are undefined. If I run a provisioning script i get:

```
  Error: pkcs7_public_key is not defined at /tmp/vagrant-puppet-1/manifests/default.pp:1 on node ubuntu-server-12042-x64-vbox4210.home
  Wrapped exception:
  pkcs7_public_key is not defined
```

You can reproduce the issue by using the test case project I've prepared and running:

```
  $ git clone git@github.com:rgladwell/test-hiera-eyaml-vagrant.git
  $ vagrant up
```

This can be fixed by explicitly setting the private keys in the `hiera.yaml` configuration file:

```
 :eyaml:
    :datadir: hiera/
        :pkcs7_public_key:  ./keys/public_key.pkcs7.pem
        :pkcs7_private_key:  ./keys/private_key.pkcs7.pem
```

**Comment by jhoblitt** [comment]
I ran into this issue as well.  I have opened PR #157 that appear to resolve it and made a fork of @rgladwell's demo that demonstrates the fix.  https://github.com/jhoblitt/test-hiera-eyaml-vagrant

**Comment by Dan33l** [comment]
it can be reopened if it's reproducible on the latest Puppet 4 or newer
