### ISSUE TITLE
 Puppet hiera(): Cannot load backend eyaml: no such file to load

### ISSUE THREAD

**Issue by sc-chad** [voxpupuli/hiera-eyaml#115]
Environment: Amazon Linux AMI
Puppet Version: 3.7.1
Puppet Server 0.3.0 (the new one) not puppetmaster
Both were installed from the puppetlabs repo.

If I use puppetmaster or something like nginx/unicorn this works fine.  But using the new puppetserver released it can't find the backend.

My hiera.yaml file

```

---
:backends:
  - eyaml
  - yaml

:hierarchy:
  - '%{::clientcert}'
  - '%{::osfamily}'
  - encrypted
  - common

:yaml:
   :datadir: /etc/puppet/modules/hieradata

:eyaml:
    :datadir: /etc/puppet/modules/hieradata
    :extension: 'yaml'

    # If using the pkcs7 encryptor (default)
    :pkcs7_private_key: /etc/somekey.pkcs7.pem
    :pkcs7_public_key:  /etc/somepubkey.pkcs7.pem
```

Full error in /var/log/puppetserver/puppetserver.log

```
Puppet hiera(): Cannot load backend eyaml: no such file to load -- hiera/backend/eyaml/encryptor
```

Doing a whereis on eyaml shows it here:

```
eyaml: /usr/local/bin/eyaml
```

I see eyaml_backend located here:

```
/usr/local/share/ruby/gems/2.0/gems/hiera-eyaml-2.0.3/lib/hiera/backend/eyaml_backend.rb
```

Not sure where else to look so I appreciate the help.  I'd like to get this running correctly.

**Comment by TomPoulton** [comment]
Hi @chad-upton, did the fix from @KevinCorcoran work?

**Comment by chad-upton** [comment]
I moved on to just using the old one served via nginx and unicorn.  I
haven't had time to circle back and try it.  I appreciate the time though.

*Chad Upton, Systems Engineer - IT @ findly*
chad.upton@findly.com
+1.405.414.6229

On Tue, Jan 13, 2015 at 11:23 AM, TomPoulton <notifications@github.com>
wrote:

> Hi @chad-upton <https://github.com/chad-upton>, did the fix from
> @KevinCorcoran <https://github.com/KevinCorcoran> work?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TomPoulton/hiera-eyaml/issues/115#issuecomment-69782514>
> .
>

-- 

------------  Our Legal Fees At Work -----------------------------------
This communication and its contents are confidential and may contain 
protected intellectual property or other information protected from 
disclosure. If you are not the intended recipient you may not read, copy, 
distribute or use this information. If you have received this 
communication or its contents in error, please notify Findly immediately by 
replying to this message and then delete this communication and its 
contents from your system.

**Comment by mlehner616** [comment]
Ran into this with Puppet Enterprise 3.7 with the hunner/puppet-hiera#46 module and running the following command resolved the issue. 

`puppetserver gem install hiera-eyaml`

**Comment by chad-upton** [comment]
I was finally able to get back around to this while working on our migration to 4.0.

With 4.0 eyaml works inside the puppet run with puppetserver gem install hiera-eyaml, but if I just try to run hiera environment or some key I get:
```
WARN: 2015-04-23 17:02:32 +0000: Cannot load backend eyaml: cannot load such file -- hiera/backend/eyaml_backend
```

**Comment by elyscape** [comment]
If you want command-line access or to be able to use the hiera command-line tool with Puppet 4, you'll need to also run `/opt/puppetlabs/bin/gem install hiera-eyaml`.

**Comment by chad-upton** [comment]
Hmm no gem under /opt/pupetlabs/bin

```
ls -alh /opt/puppetlabs/bin/
total 8.0K
drwxr-xr-x 2 root root 4.0K Apr 21 19:24 .
drwxr-xr-x 5 root root 4.0K Apr 21 19:24 ..
lrwxrwxrwx 1 root root   34 Apr 21 19:24 cfacter -> /opt/puppetlabs/puppet/bin/cfacter
lrwxrwxrwx 1 root root   33 Apr 21 19:24 facter -> /opt/puppetlabs/puppet/bin/facter
lrwxrwxrwx 1 root root   32 Apr 21 19:24 hiera -> /opt/puppetlabs/puppet/bin/hiera
lrwxrwxrwx 1 root root   30 Apr 21 19:24 mco -> /opt/puppetlabs/puppet/bin/mco
lrwxrwxrwx 1 root root   33 Apr 21 19:24 puppet -> /opt/puppetlabs/puppet/bin/puppet
lrwxrwxrwx 1 root root   44 Apr 21 19:24 puppetserver -> ../server/apps/puppetserver/bin/puppetserver
```

However there is a gem binary under /opt/puppetlabs/puppet/bin
Which I tried to do as you asked and get the same error.

**Comment by elyscape** [comment]
Where is the hiera binary you're running?

**Comment by chad-upton** [comment]
```
/opt/puppetlabs/bin/hiera
```

**Comment by chad-upton** [comment]
Here is a copy of my hiera.yaml file
```
---
:backends:
  - eyaml
  - yaml

:hierarchy:
  - "domain/%{::domain}/%{::product}"
  - "domain/%{::domain}/%{::hostname}"
  - "domain/%{::domain}/default"
  - "environment/%{::environment}/%{::product}"
  - "environment/%{::environment}/default"
  - "environment/%{::environment}/encrypted"
  - "product/%{::product}/%{::role}"
  - "product/%{::product1}/%{::role}"
  - "product/%{::product2}/%{::role}"
  - "product/%{::product3}/%{::role}"
  - "product/%{::product4}/%{::role}"
  - "product/%{::product5}/%{::role}"
  - "product/%{::product6}/%{::role}"
  - "product/%{::product7}/%{::role}"
  - "product/%{::product8}/%{::role}"
  - "product/%{::product9}/%{::role}"
  - "product/%{::product}/default"
  - '%{::clientcert}'
  - 'os/%{::operatingsystem}'
  - encrypted
  - common

:yaml:
  :datadir: /etc/puppetlabs/code/hieradata

:eyaml:
  :datadir: /etc/puppetlabs/code/hieradata
  :extension: 'yaml'

  # If using the pkcs7 encryptor (default)
  :pkcs7_private_key: /etc/puppetlabs/code/somekey.pkcs7.pem
  :pkcs7_public_key:  /etc/puppetlabs/code/somepubkey.pkcs7.pem
```

This same file is what is currently working on our 3.7.5 installation.

**Comment by rtyler** [comment]
@mlehner616's workaround fixed this error for me on Puppet Enterprise 3.7, FWIW

**Comment by chad-upton** [comment]
Yea don't think it resolves it on 4.0, at least it hasn't for me.

**Comment by elyscape** [comment]
I'll have to set up a VM with 4.0 on it and experiment.

**Comment by chad-upton** [comment]
Thanks @elyscape let me know if I can provide any other details.

**Comment by scottlackey** [comment]
We're also looking to use puppet 4.0, but we use a lot of hiera-eyaml with this same error.

**Comment by chad-upton** [comment]
So I finally got this to work on both the command line and through the server (4.1.2) I believe.

The two commands that need to be ran are:
```
/opt/puppetlabs/puppet/bin/gem install hiera-eyaml
/opt/puppetlabs/server/bin/puppetserver gem install hiera-eyaml
```

**Comment by dynek** [comment]
After hours and hours trying to understand what was going on with the fscking hiera, you guys made my day with 'puppetserver gem install'. Thanks a bunch!

**Comment by dogfish182** [comment]
All, 

I run PE 2015.2 and I was able to get this running by using the hunner/hiera module AND then running 
sudo /opt/puppetlabs/binpuppetserver gem install hiera-eyaml 

on my PE server. 

however I'm now trying  to use vagrant to setup a dev environment and eyaml is back in the toilet. I cannot load an eyaml backend by the looks and get this 

```
hiera sqlroot -c /tmp/vagrant-puppet/hiera.yaml
WARN: 2016-03-15 13:45:08 +0000: Cannot load backend eyaml: cannot load such file -- hiera/backend/eyaml_backend
nil
```
by checking the vagrant equivalent of what I could see on the puppet enterprise server I see this 

```
$ gem list 

*** LOCAL GEMS ***

bigdecimal (1.2.0)
hiera-eyaml (2.1.0)
highline (1.6.21)
io-console (0.4.2)
json (1.7.7)
psych (2.0.0)
rdoc (4.0.0)
trollop (2.1.2)
```

but running 

```
$ /opt/puppetlabs/puppet/bin/gem list
*** LOCAL GEMS ***

bigdecimal (1.2.4)
deep_merge (1.0.1)
facter (3.1.4)
hiera (3.0.6)
hocon (0.9.3)
io-console (0.4.3)
json (1.8.1)
minitest (4.7.5)
net-ssh (2.9.2)
psych (2.0.5)
puppet (4.3.2)
rake (10.1.0)
rdoc (4.1.0)
stomp (1.3.3)
test-unit (2.1.8.0)

```

NO hiera-eyaml. Attempting to install it gives me 

```
$ /opt/puppetlabs/puppet/bin/gem install hiera-eyaml
ERROR:  While executing gem ... (Errno::ENETUNREACH)
  Network is unreachable - connect(2) for "192.168.28.2" port 53
```

does anyone know how to get this thing installed under vagrant? gem installs work fine outside of puppet as do any network transactions. so I don't know why vagrant cannot reach the internet to install this one gem... 

anyone come across this? it's really annoying.

**Comment by chad-upton** [comment]
looks like you need to fix the internet connection for your vagrant box.  Can you ping google from it?

**Comment by thakkerdhawal** [comment]
hi - i have got the same problem .. puppetserver gem install - installs in /opt/puppetlabs/puppetserver whereelse hiera looks up for backend in /opt/puppetlabs/puppet.

**Comment by mgla** [comment]
Use ` /opt/puppetlabs/puppet/bin/gem install hiera-eyaml` instead. Works for me.

**Comment by pythianali** [comment]
I'm having this problem also using vagrant (1.8.5) and the puppet provisioner (3.8.6).  I ensured that hiera-eyaml gem was installed in my local gems which allowed encrypt/decrypt functionality and then also installed it using the vagrant gem (/opt/vagrant/embedded/bin/gem) and it shows up in the vagrant gem listing that binary provides.  

However this kind of error is there no matter what I do.

`==> webserver-01: Error: Evaluation Error: Error while evaluating a Function Call, Lookup of key 'apache::apache_name' failed: DataBinding 'hiera': Cannot load backend eyaml: cannot load such file -- hiera/backend/eyaml_backend at /tmp/vagrant-puppet/modules-cd17a626040a92c9c1be476468628171/profiles/manifests/webserver.pp:2:3 on node webserver-01.example.com`

So in my case it seems hiera-eyaml won't work with vagrant as the puppet provisioner doesn't seem to see the backend.  The plain old hiera yaml backend works perfectly fine in this setup and its only the eyaml backend with the issue in my case.

**Comment by 5obol** [comment]
Hey all,
We're using PuppetEnterprise 2016.2.0 and now implementing hiera-eyaml.

Our environment has no direct access to internet, all the traffic is going through proxy.
We declare the proxy host via system env http_proxy. However that's not picked up by suggested here puppetserver gem install. The error we were getting was:
[puppetserver] Puppet Evaluation Error: Error while evaluating a Function Call, Lookup of key 'some_class' failed: DataBinding 'hiera': Cannot load backend eyaml: no such file to load -- hiera/backend/eyaml_backend at /etc/puppetlabs/code/environments/production/site/profile/manifests/base.pp:8:11 on node some-node.

The solution is to use:
/opt/puppetlabs/bin/puppetserver gem install -p http://your_proxy_server.com:8080 hiera-eyaml
Hope that helps somebody.

**Comment by vStone** [comment]
Possible other solution: I build deb packages for the rubygems that need to be installed on the puppetserver with FPM. I use the following options:

```
  prefix: /opt/puppetlabs/server/data/puppetserver/jruby-gems
  depends: [puppetserver]
  gem-package-name-prefix: puppetserver-rubygem
  gem-bin-path: /opt/puppetlabs/server/data/puppetserver/jruby-gems/bin
  gem-shebang: '/usr/bin/env jruby'
  output-type: deb
```

Make sure you include the different dependencies for the gem you are packaging. I use a bundle install and loop over gems in the vendor/cache folder.

**Comment by Dan33l** [comment]
it can be reopened if it's reproducible on the latest Puppet 4 or newer
