### ISSUE TITLE
having an issue when loding hiera-eyaml

### ISSUE THREAD

**Issue by supriyawishesu** [voxpupuli/hiera-eyaml#117]
Hi 
when i run this command I am having this command when using hiera-eyaml

sudo -u pe-puppet /opt/puppet/bin/hiera -c /etc/puppetlabs/puppet/hiera.yaml --debug wls_jdk_version clientcert=weblogic.xxxx environment=test1

WARN: 2014-11-13 16:52:25 -0500: Cannot load backend eyaml: cannot load such file -- highline/import

**Comment by Dan33l** [comment]
it can be reopened if it's reproducible on the latest Puppet 4 or newer
