### ISSUE TITLE
hiera eyaml does not work on PE 3.7.2

### ISSUE THREAD

**Issue by yeayu** [voxpupuli/hiera-eyaml#126]
Hello all,

Does anyone has eyaml working on the latest version of PE? if so, how?
I have upgraded from PE 3.3 to 3.7.2, and hiera eyaml stopped working. However, hiera (no encryption) keeps working as expected
I have also tried to set it up on a fresh installation of PE 3.7.2, with the same result...

The error I receive is when i run puppet agent -t:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find data item test:password in any Hiera data file and not default supplied at /etc/puppetlabs/puppet/environments/test/modules/accounts/manifests/init.pp:2 on node mynodexxxx.domain.com
```

in that init.pp, i have configured the following:

```
 class accounts{
            $credentials = hiera('test::password')
            ...
```

in mynodexxxx.domain.com.eyaml file i have the following:

```
test::password: >
    ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEw
    DQYJKoZIhvcNAQEBBQAEggEAmAgX0ZCdwCtxQ7MkJ6FqGwhAS8mVDYAX24Pc
    lbwRZSQtQG/w0fYWiAC2KVeV6IDSIp8F/T48PJgAmK/Uq7c7bXhyPTB5mR52
    /tL9tlBhR+Wb+aaYjFmY+WLOs4kwx4k9XPHQuQmjX0wizDATaOR7E8Sojge4
    mPD3lLrpUkWT1l8Fn+5n1WI9oFDfz3GZGS5R/ITEqvMTm8t6GuWH3XZPHNyP
    j+KFQg7yBLsQYkA8WXYUtOzR+qKrJVDkKLnePRvlro5zpxhfZXZDYmUPpKHR
    PSwy4umbmo3d++E86Kn8Jy1uvyvT7jWW/CCbx3zYuIRexHsx323EitRBNiWZ
    4z9TBDA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBAMZVsKJQz6ARcePmUs
    4XytgBC6w+37Un2OQJkBi6ZQ5Ml3]
```

in hiera.yaml i have the following:

```
 :backends:
  - eyaml
  - yaml
:hierarchy:
  - "node/%{::clientcert}"
  - "%{environment}"
  - common
:yaml:
  :datadir: /etc/puppetlabs/puppet/hieradata
:eyaml:
  :datadir: /etc/puppetlabs/puppet/hieradata
  :pkcs7_private_key: '/etc/puppetlabs/puppet/keys/private_key.pkcs7.pem'
  :pkcs7_public_key: '/etc/puppetlabs/puppet/keys/public_key.pkcs7.pem'
:logger: console
```

**Comment by malnick** [comment]
Who here has actually gotten eyaml to reliably run on 3.7x?

**Comment by elyscape** [comment]
I have.

**Comment by malnick** [comment]
Awesome, I'm going through the process of trying this again. I had to drop back to 3.3 as I ran into some blockers on this a few months ago and didn't have the time to actually figure it out. I think it was a faulty gem install on the PM, so I'm trying again today.

**Comment by malnick** [comment]
Out of curiosity, can I actually execute eyaml encrypt commands on the PM (running PE not OS) or is it only available to the PM process?

**Comment by elyscape** [comment]
To be able to use `eyaml` on the command line, you'll need to also install the gem using the regular `gem` command. If you only install it via the `puppetserver gem` command, it'll only be available to the Puppet Server stack.

**Comment by malnick** [comment]
That's what I thought. On my last go around I was really confused about that.

**Comment by malnick** [comment]
Did you see something like this:

```
ERROR:  Could not find a valid gem 'hiera-eyaml' (>= 0), here is why:
Unable to download data from https://rubygems.org/ - certificate verify failed (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/hiera-eyaml-2.0.7.gemspec.rz)
ERROR:  Possible alternatives: hiera-eyaml
```

**Comment by malnick** [comment]
^^ with puppetserver gem install

**Comment by elyscape** [comment]
Are you behind a firewall that does SSL interception/inspection?

**Comment by malnick** [comment]
I'm in aws but 443 is open. My quick solution which is probably bad was:

```
 ./puppetserver gem sources -r https://rubygems.org/
 ./puppetserver gem sources -a http://rubygems.org/
````

Then the install worked fine.

**Comment by malnick** [comment]
```
Notice: hiera(): Cannot load backend eyaml: cannot load such file -- hiera/backend/eyaml_backend
```

**Comment by malnick** [comment]
^^ Installed with puppetserver, this was the point that I got to before and gave up.

**Comment by malnick** [comment]
```
---
:backends:
  - eyaml
  - yaml
:hierarchy:
  - "roles/%{role}"
  - global
  - encrypted

:yaml:
  :datadir: /etc/puppetlabs/puppet/environments/%{environment}/hieradata

:eyaml:
  :datadir: /etc/puppetlabs/puppet/environments/%{environment}/hieradata
  :pkcs7_private_key: /etc/puppetlabs/puppet/ssl/keys/private_key.pkcs7.pem
  :pkcs7_public_key: /etc/puppetlabs/puppet/ssl/keys/public_key.pkcs7.pem
  :extension: 'yaml'
```

**Comment by elyscape** [comment]
You made sure to have the keys listed in `/etc/puppetlabs/puppet/hiera.yaml`, yes?

**Comment by malnick** [comment]
This hiera config worked fine on my 3.3 master

**Comment by elyscape** [comment]
What command are you running that produces this error?

**Comment by malnick** [comment]
puppet apply -e "notice(hiera('r10k_git_key_pub'))"

**Comment by malnick** [comment]
^^ An encrypted key from encrypted.yaml. Again, a key that decrypts fine with this exact config on my 3.3 master.

**Comment by elyscape** [comment]
For `puppet apply`, you'll need to have installed the gem via `/opt/puppet/bin/gem install`.

**Comment by malnick** [comment]
So. Many. Gems. 

Ok I'll try that.

**Comment by malnick** [comment]
Oh shit! It worked! Like a boss, thanks.

**Comment by gapotts** [comment]
As have I.

**Comment by ltutar** [comment]
Following the steps described by @elyscape helped me get it working on PE2015.3.
Thanx.

**Comment by elyscape** [comment]
Just to consolidate everything:

 - To get eyaml working on a Puppet Master that uses Puppet Server:  
  `/opt/puppet/bin/puppetserver gem install hiera-eyaml`
 - To get eyaml working with `puppet apply`:  
  `/opt/puppet/bin/gem install hiera-eyaml`
 - To get the `eyaml` binary on the command line:  
  `gem install hiera-eyaml`

**Comment by jkumar19** [comment]
I am facing this same error when I run "puppet agent -t" on agent node. It is working fine with "puppet apply" on master.

**Comment by elyscape** [comment]
@jkumar19 When you run `puppet agent -t` on the node, are you running it against the master or standalone?

**Comment by jkumar19** [comment]
I am running against puppet master. I am not using standalone setup.

**Comment by Dan33l** [comment]
it can be reopened if it's reproducible on the latest Puppet 4 or newer
