### ISSUE TITLE
eyaml and templates

### ISSUE THREAD

**Issue by leshiynyc** [voxpupuli/hiera-eyaml#171]
Hi,

I have something like this :

file { '/tmp/eyaml.test': ensure => present, content => $eyamltest, }

file {'/tmp/eyaml.template.test': ensure => present, content => template('profile/eyaml.test.erb'), }

profile/eyaml.test.erb looks like this :

<%= @yamltest %>

The content gets filled ( and decrypted ) correctly in the first case, but is blank using the template. is there something I am doing wrong or is this feature is not supported by eyaml ?

**Comment by r4v5** [comment]
Do you define `@yamltest` as something that would have the same value as `$eyamltest`?

**Comment by leshiynyc** [comment]
@r4v5  I know. I noticed the typo after my second cup of coffee.

**Comment by TomPoulton** [comment]
I'm guessing we can close this issue?
