### ISSUE TITLE
PE 3.8  - sporadically failing to load eyaml backend.

### ISSUE THREAD

**Issue by brettswift** [voxpupuli/hiera-eyaml#173]
There are a bunch of issues listed on here where people have trouble getting this working.   We have had this working for a long time on two puppet masters. (Since 3.3.2). 

I must first admit we're not using the "e" part,  we're just bastardizing eyaml as a way to get a secondary yaml backend.  Maybe there's a better option here.. but puppet doesn't support this yet (as far as I know).
### Symptom

agents including the puppet master agent, will fail to load hiera-eyaml, and there is no pattern to it.

IE:  File resources that source data from our hiera-eyaml backend,  will flip flop with data, no data, data, no data etc on each puppet run..    although it's not a toggle scenario..  we may get 2-5 runs one way or the other before it changes. 

The gems are there..    puppetserver gem list shows me hiera-eyaml.

/opt/puppet/bin/gem list also shows me eyaml (manually installed I believe). 

hiera file: 

```
# managed by puppet

---
:backends:
  - eyaml
  - yaml
:logger: console
:hierarchy:
  - "host/%{::hostname_lower}"
  - "cluster/%{::cluster}/%{role}"
  - "roles/%{role}"
  - "project/%{::project}"
  - "subnet/%{::subnet}"
  - common
  - users

:yaml:
   :datadir: /etc/puppetlabs/puppet/environments/%{::environment}/hieradata


:eyaml:
   :datadir: /etc/puppetlabs/puppet/hostdata/live
   :extension: yaml
   :pkcs7_private_key: /etc/puppetlabs/puppet/keys/private_key.pkcs7.pem
   :pkcs7_public_key:  /etc/puppetlabs/puppet/keys/public_key.pkcs7.pem
```

We're also using the hunner-hiera puppet module to install this gem, but I figured I would get more help with this behaviour on this repository. 

What could I look at on PE to figure out why this would load sometimes and not load other times? 

It's also completely fine on our other puppet master,   but broken on this puppet master.  (And i just did a clean build of a new VM - so I'm pretty sure it's not a monkey on the keyboard issue). 

something is definitely different though! 

help!??

**Comment by TomPoulton** [comment]
So different runs end up with different results, even though nothing has changed, so sometimes you get a value back and sometimes you don't?

**Comment by brettswift** [comment]
Yea exactly.   Just like your little avatar was playing around in our puppet master. :) 

I'm not really sure how to go about debugging this.  We're not on puppet 2015.2 yet,  just 3.8.0. 

I'm wondering if the load path flip flops around,  but it's not a toggle,  it's very random.   For instance today, without any code pushes, we saw a data change at these times:   8:11,   10:41,  and 11:41. 

8:11 it didn't load the backend, and didn't load it until  10:41 when it did load. At 11:11 it loaded it as well (but no change was seen).  Then it didn't load the backend again at 11:41 and we see the node go blue on the console.

**Comment by TomPoulton** [comment]
Ummmmm.... have you tried looking for actual gremlins (or metal-head monkeys) living inside you servers?

Apart from looking at some kind of network level stuff like load balancers (although beyond the obvious load-balanced-masters situation I can't think how that would affect things internally too much) maybe you could setup a test node that only has one class applied to it like the one below and see if it changes?

```puppet
class bugsmashers { # StarCitizen anyone?
    $my_var = hiera('my_gremlin_var')

    notify { "$my_var": }
}
```

I know that there are some facts that can change from run to run, maybe you have some complex manifests that use these dynamic facts? Also use a value from `common.eyaml` or `users.eyaml` (if they exist) so that the hierarchy is as simple as possible

Although it sounds like sometimes your backend randomly fails to load, is that right? If so that suggests that there are some funky things going on with your puppet server!

**Comment by acjohnson** [comment]
We appear to be having similar symptoms to this bug.
Has there been any advancement on this?
Can you confirm if you are seeing a similar log in your `/var/log/pe-puppetserver/puppetserver.log` file?

```shell
ldxx90pup4: /var/log/pe-puppetserver/puppetserver.log:2016-02-16 16:55:22,721 INFO  [puppet-server] Puppet hiera(): Cannot load backend eyaml: load error: highline/import -- java.lang.NoClassDefFoundError: jline/internal/TerminalLineSettings
ldxx90pup4: /var/log/pe-puppetserver/puppetserver.log:2016-02-16 16:55:23,174 INFO  [puppet-server] Puppet hiera(): Cannot load backend eyaml: load error: highline/import -- java.lang.NoClassDefFoundError: jline/internal/TerminalLineSettings
```

**Comment by Dan33l** [comment]
it can be reopened if it's reproducible on the latest Puppet 4 or newer
