### ISSUE TITLE
hiera call from manifeast not able to locate key

### ISSUE THREAD

**Issue by k3d61** [voxpupuli/hiera-eyaml#174]
## my hiera.yaml is,

:backends:
- yaml
- eyaml
  :hierarchy:
- defaults
- "%{clientcert}"
- "%{environment}"
- global
  :logger:
- puppet

:yaml:
  :datadir: /etc/puppet/hiera/
:eyaml:
  :datadir: /etc/puppet/hiera/
  :pkcs7_private_key: /etc/puppet/keys/private_key.pkcs7.pem
  :pkcs7_public_key: /etc/puppet/keys/public_key.pkcs7.pem

I kept encrypted value in /etc/puppet/hiera/defaults.eyaml
but puppet trows error as: 
"Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find data item test in any Hiera data file and no default supplied ........"
but it woks from command line if i run, hiera -c /etc/puppet/hiera.yaml test

i folled this document, https://github.com/TomPoulton/hiera-eyaml
## my defaults.eyaml is

test: >
    ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEw
    DQYJKoZIhvcNAQEBBQAEggEArUnUlBwWv21Rs1Z8NQwhcocBpgMNYErzvn//
    Wbhp5nZnSYhhKQogH766dcc1MNEg+GptabsFaPyowPY84TlN89qrkCwZihQ3
    a45HFj7Rt6mDsWxyVLlXH1e94p9QtSBPgAElu14NFQ4bDTASGYE43Acd/mCU
    QS/STHjaVx3CEsrVPz/TryOx36ct/WOkpgZxyLlXc6wweMwqBdDmw9YNe3I2
    1nrKaY9GL5jrkH//JJcQQPJoVIoH5SnsHHapWLN5on2RRHjHGhhGJGX9LMxP
    OQH5m5kcr5fshS1JSR2gj5BnbGJsz8ZQP4Jqb3yox0I5Fge1dNZ9Zd5FM1de
    ZB0VljA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBDlORp4uD6c2iIsB8cr
    JeqNgBAKcEVKfTA3BRRdxCQHARoB]

**Comment by Dan33l** [comment]
it can be reopened if it's reproducible on the latest Puppet 4 or newer
