### ISSUE TITLE
ansible variables with eyaml?

### ISSUE THREAD

**Issue by SydOps** [voxpupuli/hiera-eyaml#194]
Are there any way to use eyaml within ansible?

**Comment by gtmtech** [comment]
Yes, I use eyaml with ansible myself. But its a bit of a hack

**Comment by SydOps** [comment]
@gtmtech 

any hints sharing to me?

**Comment by robbyoconnor** [comment]
Any blog posts on using eyaml with ansible? I'm using [git-crypt](https://github.com/AGWA/git-crypt) right now, but I'd like to open more things up a little bit more..

**Comment by gunzl1ng3r** [comment]
Got a working solution - https://www.serverraumgeschichten.de/2017/03/encrypting-single-values-in-ansible/

**Comment by SydOps** [comment]
@gunzl1ng3r 

Thanks, that's what I am waiting for so long time.
