### ISSUE TITLE
Support version 4 hiera config

### ISSUE THREAD

**Issue by mafgh** [voxpupuli/hiera-eyaml#213]
When trying to use hiera-eyaml with [hiera.yaml version 4](https://docs.puppet.com/puppet/latest/reference/lookup_quick.html#hierayaml-version-4-in-a-nutshell) I am getting the following error:

> Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: /etc/puppetlabs/code/environments/foo/hiera.yaml: No data provider is registered for backend 'eyaml'  on node puppet.bc

hiera.yaml:
    ---
    version: 4
    
    datadir: "data"
    
    hierarchy:
      - name: "node/%{trusted.certname}"
        backend: "yaml"
      - name: "encrypted"
        backend: "eyaml"
      - name: "common"
        backend: "yaml"

**Comment by athingisathing** [comment]
I am also getting this issue. @mafgh any luck?

**Comment by mafgh** [comment]
@athingisathing no. we ended up using hiera config version 3, partly because of eyaml, partly because puppet lookup gave us some strange results.

**Comment by ahpook** [comment]
The new lookup system does not support hiera-eyaml, so that's why you got the error. You can follow the work to add it here : https://tickets.puppetlabs.com/browse/PUP-7100

**Comment by pckls** [comment]
Thanks @ahpook for that link I was actually looking for that information and found it here :)

This issue is probably invalid though, the issue is with Puppet/Hiera not hiera-eyaml.

**Comment by lesinigo** [comment]
Hiera4 has been deprecated long ago and hiera-eyaml does support hiera5. I guess this issue can be closed?
