### ISSUE TITLE
secret in the logs

### ISSUE THREAD

**Issue by lovilak** [voxpupuli/hiera-eyaml#216]
Hello,

Can you tell me how to not show the decrypted secret in the log of puppet  for exemple ?

Thks,

**Comment by ahpook** [comment]
@lovilak - If you are using a recent Puppet version you can mark the values that you want to hide using the Sensitive(T) type - https://docs.puppet.com/puppet/latest/lang_data_sensitive.html

**Comment by Loshea** [comment]
I'm fairly new to puppet and hiera. How would you use Sensitive on user passwords?  You can't call the function from within Hiera (can you?), so would you modify the userclass in site.pp?  something like
class user{
  password => Sensitive(hiera('user::password'))
}
?  Or is there something else basic i'm missing?

**Comment by jglenn9k** [comment]
Watching.

**Comment by rnelson0** [comment]
The Sensitive type is helpful and could be used as @Loshea suggests, as is the [show_diff](https://docs.puppet.com/puppet/latest/configuration.html#showdiff) setting (defaults to false, but enabled with `-t` when you use `puppet agent -t`; instead try `puppet agent -t --no-show_diff`).

**Comment by rnelson0** [comment]
Closing as the question has to do with Puppet itself, not hiera-eyaml.
