### ISSUE TITLE
Still Maintained?

### ISSUE THREAD

**Issue by c33s** [voxpupuli/hiera-eyaml#218]
is this project still maintained? currently having over 50 issues and 20 open pull requests looks not that good :(

@TomPoulton having thought about handling the project over to https://github.com/puppetlabs @glarizza or https://github.com/voxpupuli @raphink?

**Comment by ahpook** [comment]
@sihil @petems are ya'll still keeping an eye on this? I agree now that vox pup is up and running it'd be cool to have more eyes on it. I admit I have not been keeping up with it very well :(

**Comment by sihil** [comment]
I'm still vaguely keeping an eye on but am unable to find the time or incentive to devote to it as I no longer use it. I was hopeful that puppet would pick this up with @TomPoulton's help (there was a discussion around this somewhere)

In the meanwhile, whilst I can't grant permissions to others, I do have access to merge PRs and push new gems and am happy to facilitate others who are able to test and verify PRs (I do not have the test environments to do so).

I can also be bribed to spend more time on this using bounty source or similar 🤑

**Comment by ahpook** [comment]
@sihil yeah we'd floated a list of interested maintainers from Puppet last April, but IMO putting it in the voxpupuli organisation would be best as it would let a team of people have commit rights and keep things moving. 

I just took a spin through the recently-updated open issues and commented on many of them; I assume people with tactical "how do i get it working" questions that are more than a year old have probably figured it out by now :) 

Looking at the PRs, there's a big batch of them with failing tests that look Ruby or Puppet version related. Seems like it'd be a great easy step to tighten up and modernise the list of Ruby and Puppet versions in .travis.yml and then re-run those PRs to see if they pass.

**Comment by raphink** [comment]
Voxpupuli sounds like a good option for this to me.

**Comment by rnelson0** [comment]
Vox Pupuli would welcome this tool. We don't have a checklist for tools, but we do for modules. [Checklist](https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli) and [sample PR](https://github.com/voxpupuli/puppet-r10k/issues/290). The only real difference would be rubygems vs forge, I believe.

**Comment by sammcj** [comment]
+1 for Voxpupuli managing this, they're a great community and I think as this is a critical security component of so many Puppet deployments it's important it continues to be properly maintained.

**Comment by TomPoulton** [comment]
Hi all, apologies as always for disappearing on you

I think Voxpupuli is a great idea, I obviously don't have the time to manage this and I want to keep the project alive and kicking with all the great community support

I don't really know how Voxpupuli works from a people perspective; anyone know how you go about migrating a project or who to talk to?

**Comment by ahpook** [comment]
@TomPoulton woo-hoo! here's the how-to: https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli

**Comment by TomPoulton** [comment]
Thanks @ahpook

Only issue might be that this is a gem rather than a module, so we'll need to figure out ruby-gems publish rights, I'll chat to some people on slack, shouldn't be an problem

**Comment by rnelson0** [comment]
@TomPoulton We're often in #voxpupuli on irc or the puppet slack, as well,
if you want some real-time interaction. As you point out we don't have the
instructions down pat for a gem yet but we're working on it! It's the same
*basic* process and we can use this to document it well.

**Comment by TomPoulton** [comment]
Cool, let's chat on slack and we can update this thread when we have a plan!
