### ISSUE TITLE
Any way to do keytab files?

### ISSUE THREAD

**Issue by jflorian** [voxpupuli/hiera-eyaml#259]
I'm quite familiar with hiera-eyaml already and use to securely keep my passwords in Git.  Now I want to tackle my Kerberos keytabs.  This is a little tricky because the files are binary and it needs to be the entire file content.  Can this be done?

**Comment by Cinderhaze** [comment]
I'll have to see if I can track down an example, but you can turn the  binary content into an encrypted blob, that you can then use as the `content =>` param, pulled from hiera... I've only done this with text before (private key files for ssh), but it should work with binary blobs...

**Comment by jflorian** [comment]
After I posted, I started thinking about using `uuencode` to help in this regard.  Of couse, I'd need to decode on the client and have to worry about ensuring security throughout that step.  Examples would definitely be welcome.  I was hoping there was already a "whole file" support mechanism somewhere that I'd missed.

**Comment by jflorian** [comment]
Oh doh!  I reread your message and I got the gist this time.  This is extremely simple actually.
````
$ eyaml encrypt -f my_keytab
````
Take stdout and paste it into Hiera to pass as a `content =>` param.  Done.  I will put together a PR to illustrate for the README.

**Comment by jflorian** [comment]
See PR#260.

**Comment by lesinigo** [comment]
This use case [is now documented in the README.md](https://github.com/voxpupuli/hiera-eyaml/blob/master/README.md#encrypting-an-entire-file), I guess this issue can be closed.
