### ISSUE TITLE
DEPRECATION - trollop gem is deprecated, need to switch to optimist

### ISSUE THREAD

**Issue by TJM** [voxpupuli/hiera-eyaml#267]
Every time I run the eyaml command line client I get a deprecation warning:

```
[DEPRECATION] This gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible.
```

https://www.ruby-toolbox.com/projects/trollop
http://manageiq.github.io/optimist/

**Comment by chadlyon** [comment]
This PR addresses this:
https://github.com/voxpupuli/hiera-eyaml/pull/268

**Comment by shazi7804** [comment]
+1

**Comment by damascenorakuten** [comment]
+1, still seeing this issue.

**Comment by sebolabs** [comment]
Same here. eyaml 2.1.0 installed that is still dependent on trollop.

**Comment by andrewalles** [comment]
Still seeing the issue, and what's strange is the error string for me doesn't even mention trollop at runtime - it makes it sound like the eyaml gem itself is being renamed. 
`$> eyaml
[DEPRECATION] This gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible.`

**Comment by sunkaraamrutha** [comment]
I see this issue and i am not sure what is the resolution for this issue. Occurs when i am using eyaml edit filename

**Comment by TJM** [comment]
For those of you that show up here looking for the fix... please note that v2.1.0 was released in March 2016 https://github.com/voxpupuli/hiera-eyaml/releases 

It will require a new release before the fix will be live. It is just a deprecation warning and can be safely ignored for now.
