### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by johanfleury** [voxpupuli/hiera-eyaml#271]
Hi folks.

The last released version is more than 2 years old now. Would you mind releasing a new version and update this project on rubygems.org?

I'd like to take advantage of the multiple changes/improvements that has been made since 2016 on this repository.

Thanks.

**Comment by ghoneycutt** [comment]
@bastelfreak The TravisCI configuration is missing the ability to push tags to rubygems.org. Adding that would make doing releases much easier.

**Comment by alexjfisher** [comment]
3.0.0 is now deployed to rubygems.  It's been too long since the last release, but hopefully everything is fine and we won't need to pull it or rush out a 3.0.1.
