### ISSUE TITLE
Editing existing eyaml don't load existing data

### ISSUE THREAD

**Issue by tiyab** [voxpupuli/hiera-eyaml#280]
Hi,

I have setup my directories as the following:

```shell
|-- control-repo
|   |-- data
|   |      `-- common.eyaml
|   |-- manifests
|   `-- site
`-- keys
    `-- public_key.pkcs7.pem
```

I have managed to encrypt a field in my file some weeks ago. But now when I edit the file with the command:
```shell
eyaml edit control-repo/data/common.eyaml
```
it opens a blank file

If I am trying to create a new file, and encrypt a value inside it, after save and quit, the file has been created but still empty.

Am I missing something?

**Comment by tiyab** [comment]
After some more tests, this is failing when editing with VSCode. If editing with VIM it is working fine.

**Comment by shoeffner** [comment]
I had the same issue, running `EDITOR="code -w" eyaml ...` solved it: --wait/-w tells VSCode to wait until the file is closed. For reference, see https://code.visualstudio.com/docs/editor/command-line .
