### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by robbat2** [voxpupuli/hiera-eyaml#361]
Hi!

Can you please release a new version, it's been 6+ months and the code has reasonable improvements.
Likely v3.5.0 as semver to account for the minor new feature of loading config from working directory.

**Comment by bastelfreak** [comment]
Hi @robbat2, could you provide a release PR maybe that bumps the changelognand the version in the gemspec?

**Comment by robbat2** [comment]
https://github.com/voxpupuli/hiera-eyaml/pull/362
