### ISSUE TITLE
Errors of yaml and no eyaml files exist. Fine if just eyaml files exist.

### ISSUE THREAD

**Issue by shawn-sterling** [voxpupuli/hiera-eyaml#82]
Hello, first off I am running:
    CentOS 6.5
    puppet-3.4.3-1.el6.noarch
    puppet-server-3.4.3-1.el6.noarch

```
gem list
hiera (1.3.2)
hiera-eyaml (2.0.1)
highline (1.6.21)
json (1.5.5)
json_pure (1.8.1)
stomp (1.2.2)
trollop (2.0)
```

My hiera.yaml looks like this:

```

---
:backends:
 - eyaml
 - yaml

:yaml:
  :datadir: /etc/puppet/environments/%{environment}/hiera/

:eyaml:
  :datadir: /etc/puppet/environments/%{environment}/hiera/
  :pkcs7_private_key: /etc/puppet/secure/private_key.pkcs7.pem
  :pkcs7_public_key: /etc/puppet/environments/master/public_key.pkcs7.pem

:hierarchy:
  - %{::clientcert}
  - %{::environment}
  - %{::stage}
  - %{::location}
  - common

:logger: console

```

When I have .yaml files (and no eyaml files) in my hiera dir I get this error:

```
Error 400 on SERVER: Error from DataBinding 'hiera' while looking up 'repo::domain::url': undefined method `read_file' for #<Hiera::Filecache:0x7f9b1aae1b60 @cache={}> on node bla
```

If I either:
    rename .yaml .eyaml *.yaml

OR if I disable eyaml from the hiera.yaml, everything works as it should.

Here is a --trace:
https://gist.github.com/shawn-sterling/9774519

If there is anything I can do to help further debug this issue let me know.

Have a good day.

-Shawn

**Comment by Dan33l** [comment]
it can be reopened if it's reproducible on the latest Puppet 4 or newer
