### ISSUE TITLE
Should be able to `edit` a new file

### ISSUE THREAD

**Issue by masochist** [voxpupuli/hiera-eyaml#84]
When I try to `eyaml edit` a new file, eyaml dies with ENOENT.  It seems reasonable that I should be able to create a new file and have things encrypted from the start.

**Comment by pillarsdotnet** [comment]
I can confirm this works in the latest gem; this issue should be closed.
@masochist ?

**Comment by masochist** [comment]
I'm afraid I'm not in a position to easily test this, so feel free to close this.

**Comment by FransUrbo** [comment]
> I can confirm this works in the latest gem; this issue should be closed.

I can also confirm that this work in v3.0.0. Than you guys!

**Comment by ahpook** [comment]
Closing, thanks for the comments!
