### ISSUE TITLE
Update to make use of Backend.datasourcefiles()

### ISSUE THREAD

**Issue by mattkenn4545** [voxpupuli/hiera-eyaml#92]
This was included in Hiera 1.3.3 and should increase performance when traversing the hierarchy. I will try to do the change myself but I can't Ruby ;). 

See https://github.com/puppetlabs/hiera/commit/37bb93b1e0825b4f8365a237ef0fea3de0afd914

**Comment by Dan33l** [comment]
it can be reopened if it's reproducible on the latest Puppet 4 or newer
