### ISSUE TITLE
Editing multiple values fails with CentOS 6.5 and system default Ruby 1.8.7

### ISSUE THREAD

**Issue by anthonyclarka2** [voxpupuli/hiera-eyaml#95]
with hiera-eyaml 2.0.2 on CentOS 6.5 latest updates.

create simple eyaml with:

eyaml encrypt -l 'test_password' -s 'password1234' >> common.eyaml

cat common.eyaml
test_password: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAV+kmvArZ4Sf0NMcOUvEuxaKnUAY/TNIo4KTWD1obN7KIEPNCDsBryTdFuj5z4+7CTm0ONIhykjB22BDv/XV0TelL4U+ZtXReqTgBtbGM3+KDh/t6t/lbqKNczKLLYmSvFs2jhgy4Ghh1xj/1Mk+i7PP3yq//lByUsFqmeG6EFrg92jcH47hByHMS04w70NO26jTmH+VqzLU3oql+9RyFl2mEZ2mgTJi3jH47QYoxfaVLYH3kBuHTMYmGSYQzL5tG16oGKpWaiuH5VkfyZnVASalvlb5xO4c/X1HdRhRg3QDuTSjfzjFK0vOsINb+esNAZmWuA9fijlbRvy/k+T0WwDA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBBugUfpDY3QIj+qQ5y6DtjogBAna/xVM/tqXymnf4XvAcPh]

OR

test_password: >
    ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEw
    DQYJKoZIhvcNAQEBBQAEggEAV+kmvArZ4Sf0NMcOUvEuxaKnUAY/TNIo4KTW
    D1obN7KIEPNCDsBryTdFuj5z4+7CTm0ONIhykjB22BDv/XV0TelL4U+ZtXRe
    qTgBtbGM3+KDh/t6t/lbqKNczKLLYmSvFs2jhgy4Ghh1xj/1Mk+i7PP3yq//
    lByUsFqmeG6EFrg92jcH47hByHMS04w70NO26jTmH+VqzLU3oql+9RyFl2mE
    Z2mgTJi3jH47QYoxfaVLYH3kBuHTMYmGSYQzL5tG16oGKpWaiuH5VkfyZnVA
    Salvlb5xO4c/X1HdRhRg3QDuTSjfzjFK0vOsINb+esNAZmWuA9fijlbRvy/k
    +T0WwDA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBBugUfpDY3QIj+qQ5y6
    DtjogBAna/xVM/tqXymnf4XvAcPh]

Edit the eyaml and delete the first value and add a yaml header thingy:

eyaml edit common.eyaml
## cat common.eyaml

test_password: >
    ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEw
    DQYJKoZIhvcNAQEBBQAEggEAV+kmvArZ4Sf0NMcOUvEuxaKnUAY/TNIo4KTW
    D1obN7KIEPNCDsBryTdFuj5z4+7CTm0ONIhykjB22BDv/XV0TelL4U+ZtXRe
    qTgBtbGM3+KDh/t6t/lbqKNczKLLYmSvFs2jhgy4Ghh1xj/1Mk+i7PP3yq//
    lByUsFqmeG6EFrg92jcH47hByHMS04w70NO26jTmH+VqzLU3oql+9RyFl2mE
    Z2mgTJi3jH47QYoxfaVLYH3kBuHTMYmGSYQzL5tG16oGKpWaiuH5VkfyZnVA
    Salvlb5xO4c/X1HdRhRg3QDuTSjfzjFK0vOsINb+esNAZmWuA9fijlbRvy/k
    +T0WwDA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBBugUfpDY3QIj+qQ5y6
    DtjogBAna/xVM/tqXymnf4XvAcPh]

Edit the eyaml again and add a second value:
## (vim window looks like this:

test_password: >
    DEC(1)::PKCS7[password1234]!
prod_password: >
    DEC(2)::PKCS7[4321drowssap]!

Save the file and get this error:

eyaml edit common.eyaml
[hiera-eyaml-core] Loaded config from /root/.eyaml/config.yaml
[hiera-eyaml-core] !!! undefined method `plain_text' for #<Hiera::Backend::Eyaml::Parser::NonMatchToken:0x7f16ab7dedf8>
[hiera-eyaml-core] ["/usr/lib/ruby/gems/1.8/gems/hiera-eyaml-2.0.2/lib/hiera/backend/eyaml/subcommands/edit.rb:70:in`execute'", "/usr/lib/ruby/gems/1.8/gems/hiera-eyaml-2.0.2/lib/hiera/backend/eyaml/subcommands/edit.rb:67:in `map'", "/usr/lib/ruby/gems/1.8/gems/hiera-eyaml-2.0.2/lib/hiera/backend/eyaml/subcommands/edit.rb:67:in`execute'", "/usr/lib/ruby/gems/1.8/gems/hiera-eyaml-2.0.2/lib/hiera/backend/eyaml/CLI.rb:45:in `execute'", "/usr/lib/ruby/gems/1.8/gems/hiera-eyaml-2.0.2/bin/eyaml:13", "/usr/bin/eyaml:19:in`load'", "/usr/bin/eyaml:19"]

(common.eyaml still looks the same as the previous cat output, nothing was saved)

**Comment by Dan33l** [comment]
it can be reopened if it's reproducible on the latest Puppet 4 or newer with ruby provided with Puppet.
